{% set version = "5.0b" %}

package:
  name: signalp5
  version: {{ version }}

build:
  number: 3
  skip: True  # [win]

requirements:
  run:
    - gzip

test:
  commands:
    - 'signalp -h || [ $? == 1 ]'
    - 'signalp5 -h || [ $? == 1 ]'
    - 'signalp5-register || [ $? == 1 ]'

about:
  home: https://services.healthtech.dtu.dk/services/SignalP-5.0#
  summary: "A placeholder library to install SignalP versions 5."
  license: Proprietary

extra:
  recipe-maintainers:
    - darcyabjones
