{% set version = "2.0" %}

package:
  name: targetp2
  version: {{ version }}

build:
  number: 3
  skip: True  # [win]

requirements:
  run:
    - gzip

test:
  commands:
    - 'targetp -h || [ $? == 1 ]'
    - 'targetp2 -h || [ $? == 1 ]'
    - 'targetp2-register || [ $? == 1 ]'

about:
  home: https://services.healthtech.dtu.dk/service.php?TargetP-2.0
  summary: "A placeholder library to install TargetP versions 2."
  license: Proprietary

extra:
  recipe-maintainers:
    - darcyabjones
